print("Escape Characters")
print("#To insert characters that are illegal in a string escape character can be used.")
print("# \' 	Single Quote") 	
print("# \\ 	Backslash") 	
print("# \n 	New Line")	
print("# \r 	Carriage Return") 	
print("# \t 	Tab") 	
print("# \b 	Backspace") 	
print("# \f 	Form Feed") 	
print("# \ooo 	Octal value") 	
# print("# \xhh 	Hex value")